package bootstrap

import (
	"context"
	"crypto/rand"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/dropDatabas3/hellojohn/internal/domain/repository"
	"github.com/dropDatabas3/hellojohn/internal/security/password"
	store "github.com/dropDatabas3/hellojohn/internal/store"
)

// AdminBootstrapConfig holds configuration for admin bootstrap.
type AdminBootstrapConfig struct {
	DAL           store.DataAccessLayer
	AdminEmail    string // HELLOJOHN_ADMIN_EMAIL — optional; auto-generated if empty
	AdminPassword string // HELLOJOHN_ADMIN_PASSWORD — optional; auto-generated if empty
	FSRoot        string // Root dir for initial-credentials.txt (default: "data")
}

// CheckAndCreateAdmin ensures at least one admin exists.
// It never blocks on stdin. Three layers:
//
//  1. If AdminEmail+AdminPassword are set → seed from env (Docker/CI/hjctl profile).
//  2. If neither is set → auto-generate credentials, write to {FSRoot}/initial-credentials.txt,
//     and log them prominently.
//
// In both cases the operation is idempotent: if an admin already exists it returns immediately.
func CheckAndCreateAdmin(ctx context.Context, cfg AdminBootstrapConfig) error {
	hasAdmin, err := hasExistingAdmin(ctx, cfg.DAL)
	if err != nil {
		return fmt.Errorf("check existing admins: %w", err)
	}
	if hasAdmin {
		return nil // fast path — normal restarts produce no noise
	}

	fsRoot := cfg.FSRoot
	if fsRoot == "" {
		fsRoot = "data"
	}

	email := cfg.AdminEmail
	pw := cfg.AdminPassword

	autoGenerated := email == "" || pw == ""
	if autoGenerated {
		// Layer 2: auto-generate
		email = "admin@localhost"
		pw, err = generateAdminPassword()
		if err != nil {
			return fmt.Errorf("generate admin password: %w", err)
		}
	}

	if err := createAdminUser(ctx, cfg.DAL, email, pw); err != nil {
		return fmt.Errorf("create admin user: %w", err)
	}

	if autoGenerated {
		credPath := filepath.Join(fsRoot, "initial-credentials.txt")
		content := fmt.Sprintf(
			"# HelloJohn initial admin credentials\n# Generated: %s\n# DELETE this file after logging in.\n\nEmail:    %s\nPassword: %s\n",
			time.Now().UTC().Format(time.RFC3339), email, pw,
		)
		_ = os.MkdirAll(filepath.Dir(credPath), 0o755)
		_ = os.WriteFile(credPath, []byte(content), 0o600)

		log.Printf("")
		log.Printf("┌─────────────────────────────────────────────┐")
		log.Printf("│  ⚠  FIRST-RUN ADMIN CREDENTIALS             │")
		log.Printf("│                                              │")
		log.Printf("│  Email:    %s", email)
		log.Printf("│  Password: %s", pw)
		log.Printf("│                                              │")
		log.Printf("│  Saved to: %s", credPath)
		log.Printf("│  Delete this file after your first login.   │")
		log.Printf("└─────────────────────────────────────────────┘")
		log.Printf("")
	} else {
		log.Printf("[bootstrap] Admin user created: %s", email)
	}

	return nil
}

// ShouldRunBootstrap returns true when no admin users exist.
func ShouldRunBootstrap(ctx context.Context, dal store.DataAccessLayer) bool {
	hasAdmin, err := hasExistingAdmin(ctx, dal)
	if err != nil {
		return false // conservative: skip on error
	}
	return !hasAdmin
}

// hasExistingAdmin checks whether at least one admin record exists.
func hasExistingAdmin(ctx context.Context, dal store.DataAccessLayer) (bool, error) {
	configAccess := dal.ConfigAccess()
	adminRepo := configAccess.Admins()
	if adminRepo == nil {
		return false, nil
	}
	admins, err := adminRepo.List(ctx, repository.AdminFilter{Limit: 1})
	if err != nil {
		return false, err
	}
	return len(admins) > 0, nil
}

// createAdminUser creates a new global admin in the Control Plane (FS or DB).
func createAdminUser(ctx context.Context, dal store.DataAccessLayer, email, plainPassword string) error {
	configAccess := dal.ConfigAccess()
	adminRepo := configAccess.Admins()
	if adminRepo == nil {
		return fmt.Errorf("AdminRepository not available (FS adapter not initialized)")
	}

	existing, err := adminRepo.GetByEmail(ctx, email)
	if err != nil && !repository.IsNotFound(err) {
		return fmt.Errorf("check existing admin: %w", err)
	}
	if existing != nil {
		return nil // already exists — idempotent
	}

	passwordHash, err := password.Hash(password.Default, plainPassword)
	if err != nil {
		return fmt.Errorf("hash password: %w", err)
	}

	_, err = adminRepo.Create(ctx, repository.CreateAdminInput{
		Email:        email,
		PasswordHash: passwordHash,
		Name:         "",
		Type:         repository.AdminTypeGlobal,
		CreatedBy:    nil,
	})
	return err
}

// generateAdminPassword produces a cryptographically random password with the
// "hjadm-" prefix followed by 20 alphanumeric characters.
func generateAdminPassword() (string, error) {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	buf := make([]byte, 20)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	for i, b := range buf {
		buf[i] = alphabet[int(b)%len(alphabet)]
	}
	return "hjadm-" + string(buf), nil
}
