CREATE TABLE IF NOT EXISTS system_settings (
    `key`        VARCHAR(128) NOT NULL PRIMARY KEY,
    `value`      JSON         NOT NULL,
    `updated_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_by` VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
